run:
  modules-download-mode: mod
  deadline: 5m

output:
  sort-results: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - gocognit
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - golint
    - goprintffuncname
    - gosec
    - govet
    - ifshort
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
  disable-all: true
  fast: false

linters-settings:
  goimports:
    local-prefixes: github.tesla.com/Factory-Software/modbustcp
